sudo : required
services : 
    - docker

before_install :
    - docker build -t louis6/react-test -f ./client/Dockerfile.dev ./client

script :
    - docker run -e CI=true louis6/react-test npm test -- --coverage

after_success :
    - docker build -t louis6docker/multi-client ./client
    - docker build -t louis6docker/multi-nginx ./nginx
    - docker build -t louis6docker/multi-server ./server
    - docker build -t louis6docker/multi-worker ./worker

    - echo $DOCKER_PWD | docker login -u $DOCKER_ID --password-stdin
    - docker push louis6docker/multi-client
    - docker push louis6docker/multi-nginx 
    - docker push louis6docker/multi-server
    - docker push louis6docker/multi-worker